96 refactor arm subsystem
Yeti-Robotics/crescendo-java-2024 pull request #104
Opened 2024-08-18 15:59 UTC by Ankit-Panda-2010

2024-08-18 16:17 UTC, drew-beamer requested changes

2024-08-18 16:17 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void setMotorsBrake() {
We don't want to expose functions like this outside of the class—anything outside of the class should be controlling the subsystem via a command. This should either return a command to move, or be private. I'd recommend following a similar pattern to `moveUpAndStop`

2024-08-18 16:17 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void moveUp(double speed) {
make this private

2024-08-18 16:17 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void stop() {
make this private

2024-08-18 16:17 UTC, drew-beamer commented on src/main/java/frc/robot/RobotContainer.java
Refactor the arm down command in this file as well--it's not utilizing a command factory atm

2024-08-18 16:21 UTC, boomermath commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void setMotorsBrake() {
Delete this function. Motor brake configuration is only ever BRAKE currently.

2024-08-18 16:31 UTC, boomermath commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void setMotorsBrake() {
Delete motorsbrake method. Motor brake config should only need to be set once in constructor

2024-08-18 16:33 UTC, boomermath commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void setMotorsBrake() {
I’d also recommend removing the moveUp and moveDown methods and just inline the code to make numbers negative/positive in command. See IntakeSubsystem

2024-08-22 19:40 UTC, samperlmutter requested changes

2024-08-22 21:23 UTC, drew-beamer requested changes

2024-08-22 21:23 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      public void setPosition(ArmConstants.ArmPositions position) {
We likely want this to be private

2024-08-22 21:23 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> -            DOWN(-15),
Do we want to use the enum for arm down?

2024-08-22 21:23 UTC, drew-beamer commented on src/main/java/frc/robot/RobotContainer.java
> +        joystick.leftBumper().onTrue(arm.moveDownAndStop(.5).until(()
Since these are all references to the arm subsystem, we might just want to create methods within it that do these. We'd avoid clogging up RobotContainer with magic numbers that way. 

`deployArm` and `stowArm` might work for naming. I would like to get @samperlmutter's thoughts as well on this.

2024-08-22 22:28 UTC, samperlmutter commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> -            DOWN(-15),
I think we should just leave it as is since the enum will become more useful once the motion magic is implemented

2024-08-22 22:45 UTC, samperlmutter commented on src/main/java/frc/robot/RobotContainer.java
> +        joystick.leftBumper().onTrue(arm.moveDownAndStop(.5).until(()
This is a good idea until the motion magic is implemented

2024-08-28 00:14 UTC, samperlmutter requested changes

2024-08-28 00:14 UTC, samperlmutter commented on src/main/java/frc/robot/RobotContainer.java
> +        joystick.leftBumper().onTrue(arm.stowArm(0.5).alongWith(pivot.movePivotPositionTo(PivotSubsystem.PivotConstants.PivotPosition.HANDOFF)));
this is for moving the arm down, so the `stowArm` should be renamed to `deployArm` or something more description

2024-08-28 00:29 UTC, qwertycloudhub approved these changes

2024-08-29 00:13 UTC, boomermath requested changes

2024-08-29 00:13 UTC, boomermath commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> -                -> getEnc() <= .02 && getEnc() >= 0), this::stop);
Maybe make .02 and 0 constants or name them? Something like deployed upper/lower bound

2024-08-29 00:13 UTC, boomermath commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> -                -> getEnc() <= .02 && getEnc() >= 0), this::stop);
Also delete getAngle method, its unused

2024-08-29 13:27 UTC, samperlmutter commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
>      }
it looks like this method is only being used in one place. can you please verify? if so, you can remove the `speed` parameter and simplify the method to hardcode in 0.5 for the speed

2024-08-30 00:21 UTC, samperlmutter approved these changes

2024-08-30 00:21 UTC, qwertycloudhub approved these changes

2024-08-30 00:24 UTC, merged