Merge "climber-development" to "development" 🐙
Yeti-Robotics/crescendo-java-2024 pull request #15
Opened 2024-02-17 21:06 UTC by yetiDS

Merge the "climber-development" branch to the main branch "development" 😭 
![image](https://github.com/Yeti-Robotics/crescendo-java-2024/assets/123520885/19c24c1f-1d6e-4529-8f1e-d26a88abfdc9)

2024-02-17 22:19 UTC, samperlmutter requested changes

2024-02-17 22:19 UTC, samperlmutter commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +        motorConfig.FutureProofConfigs = true;
@adarsh-cms This talon configuration code is not complete and does not correctly apply the configurations to the talons. Reference the ArmSubsystem for correct implementation

2024-02-24 19:06 UTC, adarsh-cms commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +        motorConfig.FutureProofConfigs = true;
Alright will correct the code with peers. Thank you.

2024-02-29 23:59 UTC, closed without merging

2024-03-01 00:00 UTC, samperlmutter commented
closed due to shooterstate-dev having more up to date climber code