Add BlinkLimeLightCommand to VisionSubsystem
Yeti-Robotics/crescendo-java-2024 pull request #65
Opened 2024-07-20 23:11 UTC by boomermath

Closes #54 and adds a trigger to IntakeSubsystem

2024-07-20 23:24 UTC, drew-beamer requested changes

2024-07-20 23:24 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
>      public void ledOn() {
Make helper methods private

2024-07-20 23:24 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
> +            sequentialCommandGroup.addCommands(blinkLightCommand);
If I'm not mistaken, this will add the same command three times, which might error. I think you'd need to make another factory to do it this way.

I'm also open to it blinking for a set duration using a deadline command, a wait command (say, 1-2 seconds), and just repeating the blink process in a repeat command. I think that might be a bit cleaner approach.

2024-07-20 23:24 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
> +import edu.wpi.first.wpilibj2.command.*;
What's the reasoning for the wildcard import?

2024-07-20 23:27 UTC, drew-beamer commented
Let's also get rid of the unused methods while we're working on `VisionSubsystem`

2024-07-21 02:17 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
> +                    new WaitCommand(VisionConstants.BLINK_DELAY),
Opinionated, but I personally prefer:

```suggestion
Commands.waitSeconds(VisionConstants.BLINK_DELAY)
```

I think it's just a bit more readable

2024-07-21 02:17 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
> +                    new WaitCommand(VisionConstants.BLINK_DELAY),
Can even do a static import 

```java
import static edu.wpi.first.wpilibj2.command.Commands.waitSeconds;
```

Then it's just

```java
waitSeconds(...)
```

2024-07-21 02:18 UTC, drew-beamer commented
@boomermath lgtm, just see the comment above--interested to see what you think. Test this on the bot on Tuesday to make sure it works.

2024-07-21 02:20 UTC, drew-beamer commented
> @boomermath lgtm, just see the comment above--interested to see what you think. Test this on the bot on Tuesday to make sure it works.

The only other _super minor_ thing would be change `BLINK_DELAY -> BLINK_DELAY_SECONDS`--would make it a bit easier to know the unit when updating the value

2024-07-21 02:24 UTC, drew-beamer commented on src/main/java/frc/robot/subsystems/VisionSubsystem.java
> +            ));
Not sure how I missed this before either, there needs to be another delay after ledOff, otherwise it'll flash off incredibly quick

2024-07-21 02:30 UTC, drew-beamer submitted a review, later dismissed

2024-07-24 00:55 UTC, qwertycloudhub approved these changes
Tested on robot, looks good

2024-07-24 00:56 UTC, drew-beamer approved these changes

2024-07-24 00:58 UTC, samperlmutter approved these changes

2024-07-24 01:08 UTC, merged